### ISSUE TITLE
apt-get unable to verify packages

### ISSUE THREAD

**Issue by paulmccarthy** [aarshad/meta-electricity-exchange#10]
When running `apt-get update` the following warning occurs:

```
W: GPG error: http://deb.debian.org jessie Release: Could not execute 'gpgv' to verify signature (is gpgv installed?)
```

When installing via apt-get, packages cannot be authenticated:

```
root@elecex-zgateway-mx6:~# apt-get install rolldice
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  rolldice
0 upgraded, 1 newly installed, 0 to remove and 54 not upgraded.
Need to get 12.0 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rolldice
Install these packages without verification? [y/N] y
Get:1 http://deb.debian.org/debian/ jessie/main rolldice armhf 1.10-5 [12.0 kB]
Fetched 12.0 kB in 0s (50.1 kB/s)
Selecting previously unselected package rolldice.
(Reading database ... 34433 files and directories currently installed.)
Preparing to unpack .../rolldice_1.10-5_armhf.deb ...
Unpacking rolldice (1.10-5) ...
Setting up rolldice (1.10-5) ...
```

gpgv is installed:

```
root@elecex-zgateway-mx6:~# which gpgv
/usr/bin/gpgv
```

**Comment by aarshad** [comment]
Hello @paulmccarthy ,
Sorry for not able to update it earlier. Actually this matter has been already addressed by yasir in the package manager related documentation. Please recheck the following readme file.

https://github.com/aarshad/meta-electricity-exchange/blob/master/docs/README_PACKAGEMANAGER.md

**Comment by paulmccarthy** [comment]
Hi @aarshad,

I had this error after I built the BSP on the 7th August using the latest sources. I'll try building it again.

Regards,
Paul.

**Comment by paulmccarthy** [comment]
Hi @aarshad,

I've just rebuilt the BSP and I'm still getting the same problem:

```
root@elecex-zgateway-mx6:~# apt-get update
Ign http://deb.debian.org jessie InRelease
Get:1 http://deb.debian.org jessie Release.gpg [2420 B]
Get:2 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie Releasenstalled in /etc/apt/trusted.gpg.d/.
Get:3 http://deb.debian.org jessie/main Translation-en [4581 kB]
Get:4 http://deb.debian.org jessie/main Sources [7063 kB]
Get:5 http://deb.debian.org jessie/main armhf Packages [6675 kB]
Fetched 18.5 MB in 18s (1019 kB/s)
Reading package lists... Done
W: GPG error: http://deb.debian.org jessie Release: Could not execute 'gpgv' to verify signature (is gpgv installed?)
```

and when trying to install a package:

```
root@elecex-zgateway-mx6:~# apt-get install rolldice
Reading package lists... Done
Building dependency tree... Done
The following NEW packages will be installed:
  rolldice
0 upgraded, 1 newly installed, 0 to remove and 54 not upgraded.
1 not fully installed or removed.
Need to get 12.0 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rolldice
Install these packages without verification? [y/N] y
Get:1 http://deb.debian.org/debian/ jessie/main rolldice armhf 1.10-5 [12.0 kB]
Fetched 12.0 kB in 0s (28.9 kB/s)
Selecting previously unselected package rolldice.
(Reading database ... 34399 files and directories currently installed.)
Preparing to unpack .../rolldice_1.10-5_armhf.deb ...
Unpacking rolldice (1.10-5) ...
Setting up mysql-server-core-5.5 (5.5.57-r0) ...
mkdir: cannot create directory '/var/lib/mysql': File exists
WARNING: The host 'elecex-zgateway-mx6' could not be looked up with resolveip.
This probably means that your libc libraries are not 100 % compatible
with this binary MySQL version. The MySQL daemon, mysqld, should work
normally with the exception that host name resolving will not work.
This means that you should use IP addresses instead of hostnames
when specifying MySQL privileges !
Installing MySQL system tables...
180820 11:10:10 [Note] /usr//sbin/mysqld (mysqld 5.5.47) starting as process 1531 ...
OK
Filling help tables...
180820 11:10:10 [Note] /usr//sbin/mysqld (mysqld 5.5.47) starting as process 1538 ...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER !
To do so, start the server, then issue the following commands:

/usr//bin/mysqladmin -u root password 'new-password'
/usr//bin/mysqladmin -u root -h elecex-zgateway-mx6 password 'new-password'

Alternatively you can run:
/usr//bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the manual for more instructions.

You can start the MySQL daemon with:
cd /usr/ ; /usr//bin/mysqld_safe &

You can test the MySQL daemon with mysql-test-run.pl
cd /usr//mysql-test ; perl mysql-test-run.pl

Please report any problems at http://bugs.mysql.com/

Setting up rolldice (1.10-5) ...
root@elecex-zgateway-mx6:~#
```

**Comment by paulmccarthy** [comment]
Hi @aarshad,

After rebooting and trying to add the gpg key again, I was able to get apt-get working. I don't know why it didn't work first time.

I'll close this issue.

Thanks,
Paul.

**Comment by paulmccarthy** [comment]
Figured out the problem:

```
gpg --keyserver pgpkeys.mit.edu --recv-key 8B48AD6246925553
```

doesn't always work because the `pgpkeys.mit.edu` server doesn't always respond. It's very flaky and it can take a number of attempts to actually get the required key.

Key can be found here: https://gist.github.com/paulmccarthy/4ecdd5f99602b854414953931a0ac072
